---
- name: Install pkgs
  package:
    name:
      - htcondor-ce-client
      - htcondor-ce-view
      - htcondor-ce
      - "htcondor-ce-{{ htcondor_ce_batch_system }}"

- name: Copy certificates
  copy:
    src: "/etc/grid-security/host{{ item }}.pem"
    dest: "/etc/grid-security/condor{{ item }}.pem"
    remote_src: true
    owner: condor
    group: condor
  loop:
    - cert
    - key

- name: Configure HTCondor CE
  template:
    src: "{{ item.src }}"
    dest: "/etc/condor-ce/{{ item.dest }}"
  loop:
    - src: ce-site-security.conf.j2
      dest: config.d/59-site-security.conf
    - src: configured-attributes.conf.j2
      dest: 60-configured-attributes.conf
    - src: job-routes.conf.j2
      dest: config.d/61-job-routes.conf
  notify: reconfigure htcondor_ce

- name: Enable Scitoken Auth
  block:
    - replace:
        path: /etc/condor-ce/config.d/01-ce-auth.conf
        regexp: '# AUTH_SSL_'
        replace: 'AUTH_SSL_'
    - template:
        src: scitokens.conf.j2
        dest: /etc/condor-ce/mapfiles.d/10-scitokens.conf

- name: Start HTCondor CE
  service:
    name: condor-ce
    state: started
    enabled: true
  register: service_condor_ce
