---
# tasks file for hephyvienna.htcondor-ce
- name: Install repositories
  include_tasks: repos.yml
  when: htcondor_ce_repo_install

- name: Prepare HTCondor CE system
  include_tasks: "{{ step }}.yml"

